name: DESIGNREHAB
favicon: null
layout_spectrum: 0.9079902730882168
typography_spectrum: 0.12998615368269384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4b5264'
    - '#eae7de'
    - '#6c6a6d'
    - '#b8b8ba'
    - '#794246'
  brandStrength: 0.1875
  lightness: 0.5865724654868245
  saturation: 0.9220531249884516
  rhythmicContrast: 0.5938970376737416
purpose: []
